"""Supervision capture — material for the offline critic (see dev ADR 0003).

Three capture modes: flagged tenants (SUPERVISED_TENANTS) get every turn stored;
brand-new tenants get their first ONBOARDING_TURNS turns captured unconditionally
(aicoach-dev#15 — the funnel breaks here, and those turns never trip a signal);
everyone else only contributes turns that tripped a problem signal, plus a small
random control sample so the rubric doesn't drift toward only ever seeing bad cases.

This is the one place in the system that stores the *content* of a разбор, so:
content is Fernet-encrypted at rest with the same MEMORY_ENCRYPTION_KEY, the
tenant is the same hash used everywhere else, and rows expire after
SUPERVISION_RETENTION_DAYS.

Never raises into the coaching flow — a failed capture must not cost a user their answer.
"""

import asyncio
import json
import os
import random
import sqlite3
import time
from pathlib import Path

DB_FILE = Path(os.environ.get("SUPERVISION_DB", "supervision.db"))
RETENTION_DAYS = int(os.environ.get("SUPERVISION_RETENTION_DAYS", "90"))
SAMPLE_PCT = int(os.environ.get("SUPERVISION_SAMPLE_PCT", "5"))
SUPERVISED = {t.strip() for t in os.environ.get("SUPERVISED_TENANTS", "").split(",") if t.strip()}

# A разбор is "substantial" past this much user input — below it, a short answer
# and an empty memory are normal, not a signal.
SUBSTANTIAL_CHARS = 500
SHORT_ANSWER_CHARS = 600

# First N turns of a brand-new tenant are captured unconditionally (aicoach-dev#15).
# The funnel breaks here — most new tenants don't get past message one, and those
# turns never trip a problem signal (nothing wrong with a short first exchange).
# "New" is self-referential: a tenant with fewer stored cases than this is new.
ONBOARDING_TURNS = 3

_SCHEMA = """
CREATE TABLE IF NOT EXISTS cases (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    ts          REAL NOT NULL,
    day         INTEGER NOT NULL,
    tenant      TEXT NOT NULL,       -- same hashed tenant id used everywhere
    skill       TEXT,                -- skill actually applied (via load_skill)
    reasons     TEXT NOT NULL,       -- why captured: budget,short_answer,no_memory_write,full,control,onboarding
    user_len    INTEGER NOT NULL,
    answer_len  INTEGER NOT NULL,
    tools       TEXT,                -- tool names called this turn
    payload     BLOB NOT NULL,       -- Fernet(json{user, answer}) or plain json
    reviewed    INTEGER NOT NULL DEFAULT 0,
    verdict     TEXT,                -- critic's itemised findings
    turn_id     TEXT                 -- opaque turn identifier generated by the bot per flush
);
CREATE INDEX IF NOT EXISTS idx_cases_reviewed ON cases(reviewed);
CREATE INDEX IF NOT EXISTS idx_cases_day      ON cases(day);

CREATE TABLE IF NOT EXISTS passes (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    ts             REAL NOT NULL,
    day            INTEGER NOT NULL,
    tenant         TEXT NOT NULL,
    tool_names     TEXT,                -- CSV: recall,save_memory,edit_memory
    write_count    INTEGER DEFAULT 0,   -- successful save/edit calls
    write_attempts INTEGER DEFAULT 0,   -- total save/edit attempts
    recall_count   INTEGER DEFAULT 0,
    crashed        INTEGER DEFAULT 0,   -- 0/1
    error          TEXT,                -- if crashed=1
    payload        BLOB                 -- Fernet(json{user, answer, summary}) or plain
);
CREATE INDEX IF NOT EXISTS idx_passes_tenant ON passes(tenant);
CREATE INDEX IF NOT EXISTS idx_passes_day    ON passes(day);

CREATE TABLE IF NOT EXISTS ratings (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    ts       REAL NOT NULL,
    tenant   TEXT NOT NULL,
    turn_id  TEXT NOT NULL UNIQUE,   -- one rating per turn; re-press replaces
    rating   TEXT NOT NULL           -- scale value: hit / partial / miss
);
CREATE INDEX IF NOT EXISTS idx_ratings_turn_id ON ratings(turn_id);

-- What a person said about the service itself, asked once by the bot after the
-- FEEDBACK_AFTER_TURN-th turn. Not a coaching turn and not a personal fact: it
-- is testimony about the product, given voluntarily in answer to our question.
-- chat_id is stored raw and on purpose — an отзыв that cannot be traced to a
-- real account is worth nothing as proof that we did not write it ourselves.
CREATE TABLE IF NOT EXISTS feedback (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    ts       REAL NOT NULL,
    tenant   TEXT NOT NULL,
    chat_id  TEXT NOT NULL,
    text     BLOB NOT NULL           -- Fernet(text) or plain, like case payloads
);
"""


def _fernet():
    key = os.environ.get("MEMORY_ENCRYPTION_KEY", "")
    if not key:
        return None
    from cryptography.fernet import Fernet
    return Fernet(key.encode() if isinstance(key, str) else key)


def _conn():
    c = sqlite3.connect(DB_FILE, timeout=5)
    c.execute("PRAGMA journal_mode=WAL")
    return c


def init():
    with _conn() as c:
        c.executescript(_SCHEMA)
        # Migration: add turn_id for DBs created before aicoach-dev#13.
        # ALTER TABLE fails silently if the column already exists (fresh or
        # already-migrated DB) — that's the intended behaviour.
        try:
            c.execute("ALTER TABLE cases ADD COLUMN turn_id TEXT")
        except sqlite3.OperationalError:
            pass


def _case_count(tenant):
    """How many cases this tenant already has stored. The definition of 'new'
    is self-referential (aicoach-dev#15): a tenant with fewer than
    ONBOARDING_TURNS stored cases is new, so their first turns land in the
    layer regardless of signals. Returns ONBOARDING_TURNS on error so the
    onboarding rule degrades to a no-op, not a double-capture."""
    try:
        with _conn() as c:
            return c.execute(
                "SELECT COUNT(*) FROM cases WHERE tenant = ?", (tenant,)
            ).fetchone()[0]
    except Exception:
        return ONBOARDING_TURNS


def reasons_for(tenant, user_len, answer_len, tools_used, budget_exhausted):
    """Why (if at all) this turn is worth keeping. Empty list = don't store."""
    if tenant in SUPERVISED:
        return ["full"]

    if _case_count(tenant) < ONBOARDING_TURNS:
        return ["onboarding"]

    out = []
    if budget_exhausted:
        out.append("budget")
    if user_len > SUBSTANTIAL_CHARS and answer_len < SHORT_ANSWER_CHARS:
        out.append("short_answer")
    # no_memory_write removed (aicoach-dev#11): after #10 moved memory writes
    # to the recollect pass, the coach never calls save_memory, so this signal
    # would fire on every turn. The signal now lives in pass_stats() instead.
    if not out and random.randint(1, 100) <= SAMPLE_PCT:
        out.append("control")  # keep the critic calibrated on normal sessions too
    return out


def capture(tenant, user_text, answer, *, skill=None, tools_used=(), budget_exhausted=False,
            turn_id=None):
    """Store a turn if it qualifies. Fire-and-forget: never raises."""
    try:
        reasons = reasons_for(tenant, len(user_text), len(answer), tools_used, budget_exhausted)
        if not reasons:
            return
        blob = json.dumps({"user": user_text, "answer": answer}, ensure_ascii=False).encode()
        f = _fernet()
        if f:
            blob = f.encrypt(blob)
        now = time.time()
        with _conn() as c:
            c.execute(
                "INSERT INTO cases (ts, day, tenant, skill, reasons, user_len, answer_len, tools, payload, turn_id) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (now, int(now // 86400), tenant, skill, ",".join(reasons),
                 len(user_text), len(answer), ",".join(tools_used), blob, turn_id),
            )
    except Exception as exc:
        print("[supervision] capture error:", exc, flush=True)


# Keep strong refs — a bare create_task can be garbage-collected mid-flight.
_tasks: set[asyncio.Task] = set()


def capture_async(*args, **kwargs):
    """Capture off the event loop. Supervision must never sit between the model
    and the person waiting for their разбор — sqlite+Fernet is disk work, and this
    service runs a single uvicorn worker, so a sync call here would stall every
    concurrent session. Losing a case on shutdown is an acceptable trade."""
    task = asyncio.create_task(asyncio.to_thread(capture, *args, **kwargs))
    _tasks.add(task)
    task.add_done_callback(_tasks.discard)


def capture_no_write(tenant, user_text, answer, write_attempts=0):
    """Queue a specific case when the recollect pass wrote nothing
    (aicoach-dev#11 follow-up). pass_stats().no_write is an aggregate — it
    says "something's off this week" but not which turn. This puts the
    actual turn in front of the critic, same as the old turn-based
    no_memory_write signal did before #10 moved writes out of the turn.

    A tried-and-failed write (write_attempts > 0, e.g. every save_memory
    call rejected by a gate) is always a signal, regardless of input length
    — the pass attempted something and it didn't land. Below
    SUBSTANTIAL_CHARS with zero attempts, an empty write is normal: the
    turn simply had nothing worth remembering."""
    if write_attempts == 0 and len(user_text) <= SUBSTANTIAL_CHARS:
        return
    try:
        blob = json.dumps({"user": user_text, "answer": answer}, ensure_ascii=False).encode()
        f = _fernet()
        if f:
            blob = f.encrypt(blob)
        now = time.time()
        with _conn() as c:
            c.execute(
                "INSERT INTO cases (ts, day, tenant, skill, reasons, user_len, answer_len, tools, payload) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (now, int(now // 86400), tenant, None, "no_memory_write",
                 len(user_text), len(answer), "", blob),
            )
    except Exception as exc:
        print("[supervision] capture_no_write error:", exc, flush=True)


def capture_no_write_async(*args, **kwargs):
    """Capture off the event loop. Like capture_async."""
    task = asyncio.create_task(asyncio.to_thread(capture_no_write, *args, **kwargs))
    _tasks.add(task)
    task.add_done_callback(_tasks.discard)


def log_pass(tenant, *, tool_names=(), write_count=0, write_attempts=0,
             recall_count=0, crashed=False, error=None, user_text=None, answer=None):
    """Log a memory extraction pass. Fire-and-forget: never raises.

    Tracks what the recollect pass did after a coaching turn — which tools it
    called, how many writes succeeded, whether it crashed. Separate from cases
    (the coaching turn itself) so the no_memory_write signal can check pass
    results instead of turn tools (aicoach-dev#11).
    """
    try:
        summary = {
            "tool_names": list(tool_names),
            "write_count": write_count,
            "write_attempts": write_attempts,
            "recall_count": recall_count,
        }
        blob = json.dumps({"user": user_text, "answer": answer, "summary": summary},
                          ensure_ascii=False).encode()
        f = _fernet()
        if f:
            blob = f.encrypt(blob)
        now = time.time()
        with _conn() as c:
            c.execute(
                "INSERT INTO passes (ts, day, tenant, tool_names, write_count, "
                "write_attempts, recall_count, crashed, error, payload) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (now, int(now // 86400), tenant, ",".join(tool_names),
                 write_count, write_attempts, recall_count, int(crashed), error, blob),
            )
    except Exception as exc:
        print("[supervision] log_pass error:", exc, flush=True)


def log_pass_async(*args, **kwargs):
    """Log pass off the event loop. Like capture_async."""
    task = asyncio.create_task(asyncio.to_thread(log_pass, *args, **kwargs))
    _tasks.add(task)
    task.add_done_callback(_tasks.discard)


def _decode(blob):
    f = _fernet()
    if f:
        blob = f.decrypt(blob)
    return json.loads(blob)


def pending(limit=50, tenant=None):
    """Un-reviewed cases, oldest first, with content decrypted. Optionally scoped
    to one tenant. Carries the person's rating (if any) via LEFT JOIN — for the
    operator to read beside the trace, not for the critic's prompt: see
    supervise._headline for why the two must stay apart."""
    where = "c.reviewed = 0" + (" AND c.tenant = ?" if tenant else "")
    params = ([tenant, limit] if tenant else [limit])
    with _conn() as c:
        rows = c.execute(
            f"SELECT c.id, c.ts, c.tenant, c.skill, c.reasons, c.tools, c.payload, "
            f"c.turn_id, r.rating "
            f"FROM cases c LEFT JOIN ratings r ON c.turn_id = r.turn_id "
            f"WHERE {where} ORDER BY c.ts LIMIT ?", params
        ).fetchall()
    out = []
    for cid, ts, tenant, skill, reasons, tools_used, payload, turn_id, rating in rows:
        try:
            body = _decode(payload)
        except Exception as exc:
            print(f"[supervision] case {cid} unreadable:", exc, flush=True)
            continue
        out.append({"id": cid, "ts": ts, "tenant": tenant, "skill": skill,
                    "reasons": reasons, "tools": tools_used,
                    "user": body["user"], "answer": body["answer"],
                    "turn_id": turn_id, "rating": rating})
    return out


def mark_reviewed(case_id, verdict):
    with _conn() as c:
        c.execute("UPDATE cases SET reviewed = 1, verdict = ? WHERE id = ?", (verdict, case_id))


def purge(days=RETENTION_DAYS):
    """Drop cases and passes past retention, plus the ratings that went with
    them. A rating whose case is gone is unreadable anyway — «мимо» means
    nothing without the trace it points at — so it must not outlive it.

    Отзывы are not on retention: they are evidence, and evidence that expires
    after 90 days is not evidence."""
    cutoff = int(time.time() // 86400) - days
    with _conn() as c:
        cur = c.execute("DELETE FROM cases WHERE day < ?", (cutoff,))
        c.execute("DELETE FROM passes WHERE day < ?", (cutoff,))
        c.execute("DELETE FROM ratings WHERE ts < ?", (cutoff * 86400,))
        return cur.rowcount


# Sentinel that replaces the tenant hash once a person asks to be deleted. All
# deleted people collapse into one bucket, so nothing groups back into a person.
DELETED_TENANT = "(deleted)"


def forget_tenant(tenant):
    """Erase everything a person said, keep what we learned from it.

    /delete_my_data must remove the conversation itself: `payload` holds the
    verbatim ход, and `verdict` is the critic's write-up of it, which quotes.
    Both are cleared, and the tenant hash is replaced by a sentinel so the rows
    can never be grouped back into a person.

    What survives is deliberately not about the person: the rating («в точку /
    частично / мимо») and the structured trace beside it — which tools the coach
    called, how much recall found, which skill ran. That is product experience,
    not a personal fact, and it is the only prospective signal we have about
    where the coach is wrong. Keeping it costs the person nothing: it no longer
    contains their words and no longer points at them.

    The `feedback` table is untouched on purpose. An отзыв is testimony about
    the service, given voluntarily in answer to our question — not part of the
    разговор being deleted — and it keeps its chat_id, or it stops working as
    proof that we did not invent it. /privacy says so in as many words; if that
    ever stops being true there, this has to change with it.

    Returns how many rows were anonymised. Never raises — deletion must not fail
    because the quality layer had a bad day."""
    try:
        with _conn() as c:
            # reviewed = 1: there is nothing left to review. Without it the
            # emptied cases sit in pending() forever, failing to decode on every
            # supervision run.
            cur = c.execute(
                "UPDATE cases SET payload = ?, verdict = NULL, reviewed = 1, "
                "tenant = ? WHERE tenant = ?",
                (b"", DELETED_TENANT, tenant),
            )
            c.execute(
                "UPDATE passes SET payload = ?, tenant = ? WHERE tenant = ?",
                (b"", DELETED_TENANT, tenant),
            )
            c.execute("UPDATE ratings SET tenant = ? WHERE tenant = ?",
                      (DELETED_TENANT, tenant))
            return cur.rowcount
    except Exception as exc:
        print("[supervision] forget_tenant error:", exc, flush=True)
        return 0


def stats():
    with _conn() as c:
        total = c.execute("SELECT COUNT(*) FROM cases").fetchone()[0]
        waiting = c.execute("SELECT COUNT(*) FROM cases WHERE reviewed = 0").fetchone()[0]
        by_reason = c.execute(
            "SELECT reasons, COUNT(*) FROM cases GROUP BY reasons ORDER BY 2 DESC"
        ).fetchall()
        # per-tenant breakdown drives the "which tenant, is there enough?" decision
        by_tenant = c.execute(
            "SELECT tenant, COUNT(*), SUM(CASE WHEN reviewed = 0 THEN 1 ELSE 0 END) "
            "FROM cases GROUP BY tenant ORDER BY 3 DESC"
        ).fetchall()
    return {"total": total, "pending": waiting, "by_reason": by_reason,
            "by_tenant": by_tenant}


def pass_stats(days=7):
    """Stats for memory extraction passes over the last N days.

    The no_memory_write signal now lives here (aicoach-dev#11): a pass that ran
    but wrote nothing (write_count=0, crashed=0) is the new signal, replacing
    the old turn-based check that broke after memory writes moved out of the
    coaching turn (#10).
    """
    cutoff = time.time() - days * 86400
    with _conn() as c:
        total = c.execute("SELECT COUNT(*) FROM passes WHERE ts > ?", (cutoff,)).fetchone()[0]
        crashed = c.execute("SELECT COUNT(*) FROM passes WHERE ts > ? AND crashed = 1",
                            (cutoff,)).fetchone()[0]
        no_write = c.execute(
            "SELECT COUNT(*) FROM passes WHERE ts > ? AND write_count = 0 AND crashed = 0",
            (cutoff,)
        ).fetchone()[0]
        by_tenant = c.execute(
            "SELECT tenant, COUNT(*), SUM(CASE WHEN write_count > 0 THEN 1 ELSE 0 END) "
            "FROM passes WHERE ts > ? GROUP BY tenant ORDER BY 2 DESC",
            (cutoff,)
        ).fetchall()
    return {"total": total, "crashed": crashed, "no_write": no_write, "by_tenant": by_tenant}


def save_rating(tenant, turn_id, rating):
    """Upsert a user rating for a turn. Re-press replaces, never duplicates. Never raises."""
    try:
        now = time.time()
        with _conn() as c:
            c.execute(
                "INSERT INTO ratings (ts, tenant, turn_id, rating) VALUES (?, ?, ?, ?) "
                "ON CONFLICT(turn_id) DO UPDATE SET ts=excluded.ts, rating=excluded.rating",
                (now, tenant, turn_id, rating),
            )
    except Exception as exc:
        print("[supervision] save_rating error:", exc, flush=True)


def save_feedback(tenant, chat_id, text):
    """Store an answer to the product question. Never raises.

    Lives here, not in the bot's product store, for one reason: the store is
    popped wholesale by /delete_my_data, and an отзыв that disappears the moment
    someone clears their разговоры is useless as evidence that the отзывы are
    real. Deliberately outside forget_tenant and outside purge — see both."""
    try:
        blob = text.encode("utf-8")
        f = _fernet()
        if f:
            blob = f.encrypt(blob)
        with _conn() as c:
            c.execute("INSERT INTO feedback (ts, tenant, chat_id, text) VALUES (?, ?, ?, ?)",
                      (time.time(), tenant, str(chat_id), blob))
    except Exception as exc:
        print("[supervision] save_feedback error:", exc, flush=True)


def feedback(limit=100):
    """Collected отзывы, freshest first — for reading them, not for the critic."""
    f = _fernet()
    with _conn() as c:
        rows = c.execute("SELECT ts, chat_id, text FROM feedback "
                         "ORDER BY ts DESC LIMIT ?", (limit,)).fetchall()
    out = []
    for ts, chat_id, blob in rows:
        try:
            text = (f.decrypt(blob) if f else blob).decode("utf-8")
        except Exception as exc:
            print("[supervision] feedback decode error:", exc, flush=True)
            continue
        out.append({"ts": ts, "chat_id": chat_id, "text": text})
    return out


def get_rating(turn_id):
    """Return the rating for a turn ('hit'/'partial'/'miss'), or None if not yet rated."""
    try:
        with _conn() as c:
            row = c.execute(
                "SELECT rating FROM ratings WHERE turn_id = ?", (turn_id,)
            ).fetchone()
        return row[0] if row else None
    except Exception as exc:
        print("[supervision] get_rating error:", exc, flush=True)
        return None
